[package]
name = "nts"
version = "0.1.0"
authors = ["Watson Ladd <watson@cloudflare.com>"]
edition = "2018"

[dependencies]
libc = "0.2.49"
tokio =  "0.1.15"
tokio-rustls = "0.9.0"
clap = "2.32.0"
config = "0.9"